services:
  hoi-mysql:
    image: hoi4tech/hoi-mysql:latest
    ports:
      - "3306:3306"
    networks:
      - my_network
    restart: on-failure
  hoi:
    image: hoi4tech/hoi-scaffold:latest
    ports:
      - "80:8080"
    restart: on-failure
    networks:
      - my_network
    depends_on:
      hoi-mysql:
        condition: service_healthy
networks:
  my_network: